/**
 * ГЕНЕРИРУЕТСЯ автоматически — backend/scripts/build-wizard-ui-strings.ts.
 * Не редактировать руками: правки уйдут при следующей сборке. Источник —
 * frontend/src/dictionaries/*.json, список ключей — в самом скрипте.
 */

export const WIZARD_UI_STRINGS: Record<string, Record<string, string>> = {
  ru: {
    'clientSiteWizard.stepUrl': 'Ссылка',
    'clientSiteWizard.stepRecord': 'Запись',
    'clientSiteWizard.stepReview': 'Просмотр',
    'clientSiteWizard.exploreButton': 'Исследовать',
    'clientSiteWizard.fillOnlyButton': 'Только заполнить поля, без нажатия',
    'clientSiteWizard.loginButton': 'Войти',
    'clientSiteWizard.liveButton': 'Живой вход',
    'clientSiteWizard.liveDoneButton': 'Я вошёл — продолжить',
    'clientSiteWizard.liveRestartButton': 'Начать живой вход заново',
    'clientSiteWizard.undoButton': 'Отменить шаг',
    'clientSiteWizard.doneButton': 'Готово',
    'clientSiteWizard.submitButton': 'Отправить на проверку',
    'clientSiteWizard.resumeButton': 'Вернуть в работу',
    'clientSiteWizard.continueButton': 'Продолжить запись',
    'clientSiteWizard.discardButton': 'Удалить черновик',
    'wizardGuide.hintUseless': 'Тут непонятно',
    'greetingVideoWizard.startSessionButton': 'Начать сборку ролика',
    'greetingVideoWizard.generateScriptButton': 'Сгенерировать сценарий',
    'greetingVideoWizard.generateVideoButton': 'Сгенерировать видео',
    'greetingVideoWizard.referencesHeading': 'Референс-изображения',
    'greetingVideoWizard.scriptHeading': 'Сценарий',
    'greetingVideoWizard.videoHeading': 'Видео',
    'greetingVideoWizard.submitButton': 'Создать проект',
    'generationWizard.postprodCtaButton': 'Открыть в Постпрод',
  },
  uk: {
    'clientSiteWizard.stepUrl': 'Посилання',
    'clientSiteWizard.stepRecord': 'Запис',
    'clientSiteWizard.stepReview': 'Перегляд',
    'clientSiteWizard.exploreButton': 'Дослідити',
    'clientSiteWizard.fillOnlyButton': 'Лише заповнити поля, без натискання',
    'clientSiteWizard.loginButton': 'Увійти',
    'clientSiteWizard.liveButton': 'Живий вхід',
    'clientSiteWizard.liveDoneButton': 'Я увійшов — продовжити',
    'clientSiteWizard.liveRestartButton': 'Почати живий вхід заново',
    'clientSiteWizard.undoButton': 'Скасувати крок',
    'clientSiteWizard.doneButton': 'Готово',
    'clientSiteWizard.submitButton': 'Надіслати на перевірку',
    'clientSiteWizard.resumeButton': 'Повернути в роботу',
    'clientSiteWizard.continueButton': 'Продовжити запис',
    'clientSiteWizard.discardButton': 'Видалити чернетку',
    'wizardGuide.hintUseless': 'Тут незрозуміло',
    'greetingVideoWizard.startSessionButton': 'Почати збірку ролика',
    'greetingVideoWizard.generateScriptButton': 'Згенерувати сценарій',
    'greetingVideoWizard.generateVideoButton': 'Згенерувати відео',
    'greetingVideoWizard.referencesHeading': 'Референс-зображення',
    'greetingVideoWizard.scriptHeading': 'Сценарій',
    'greetingVideoWizard.videoHeading': 'Відео',
    'greetingVideoWizard.submitButton': 'Створити проєкт',
    'generationWizard.postprodCtaButton': 'Відкрити в Постпрод',
  },
  en: {
    'clientSiteWizard.stepUrl': 'Link',
    'clientSiteWizard.stepRecord': 'Recording',
    'clientSiteWizard.stepReview': 'Review',
    'clientSiteWizard.exploreButton': 'Explore',
    'clientSiteWizard.fillOnlyButton': 'Only fill the fields, no click',
    'clientSiteWizard.loginButton': 'Sign in',
    'clientSiteWizard.liveButton': 'Live sign-in',
    'clientSiteWizard.liveDoneButton': "I'm in — continue",
    'clientSiteWizard.liveRestartButton': 'Start live sign-in over',
    'clientSiteWizard.undoButton': 'Undo step',
    'clientSiteWizard.doneButton': 'Done',
    'clientSiteWizard.submitButton': 'Send for review',
    'clientSiteWizard.resumeButton': 'Return to editing',
    'clientSiteWizard.continueButton': 'Continue recording',
    'clientSiteWizard.discardButton': 'Delete draft',
    'wizardGuide.hintUseless': 'This is unclear',
    'greetingVideoWizard.startSessionButton': 'Start building the video',
    'greetingVideoWizard.generateScriptButton': 'Generate script',
    'greetingVideoWizard.generateVideoButton': 'Generate video',
    'greetingVideoWizard.referencesHeading': 'Reference images',
    'greetingVideoWizard.scriptHeading': 'Script',
    'greetingVideoWizard.videoHeading': 'Video',
    'greetingVideoWizard.submitButton': 'Create project',
    'generationWizard.postprodCtaButton': 'Open in Postprod',
  },
  de: {
    'clientSiteWizard.stepUrl': 'Link',
    'clientSiteWizard.stepRecord': 'Aufnahme',
    'clientSiteWizard.stepReview': 'Überprüfung',
    'clientSiteWizard.exploreButton': 'Untersuchen',
    'clientSiteWizard.fillOnlyButton': 'Nur Felder ausfüllen, ohne Klick',
    'clientSiteWizard.loginButton': 'Anmelden',
    'clientSiteWizard.liveButton': 'Live-Anmeldung',
    'clientSiteWizard.liveDoneButton': 'Ich bin drin — weiter',
    'clientSiteWizard.liveRestartButton': 'Live-Anmeldung neu starten',
    'clientSiteWizard.undoButton': 'Schritt rückgängig',
    'clientSiteWizard.doneButton': 'Fertig',
    'clientSiteWizard.submitButton': 'Zur Prüfung senden',
    'clientSiteWizard.resumeButton': 'Zurück in Bearbeitung',
    'clientSiteWizard.continueButton': 'Aufzeichnung fortsetzen',
    'clientSiteWizard.discardButton': 'Entwurf löschen',
    'wizardGuide.hintUseless': 'Das ist unklar',
    'greetingVideoWizard.startSessionButton': 'Video-Erstellung starten',
    'greetingVideoWizard.generateScriptButton': 'Skript generieren',
    'greetingVideoWizard.generateVideoButton': 'Video generieren',
    'greetingVideoWizard.referencesHeading': 'Referenzbilder',
    'greetingVideoWizard.scriptHeading': 'Skript',
    'greetingVideoWizard.videoHeading': 'Video',
    'greetingVideoWizard.submitButton': 'Projekt erstellen',
    'generationWizard.postprodCtaButton': 'In Postprod öffnen',
  },
  es: {
    'clientSiteWizard.stepUrl': 'Enlace',
    'clientSiteWizard.stepRecord': 'Grabación',
    'clientSiteWizard.stepReview': 'Revisión',
    'clientSiteWizard.exploreButton': 'Explorar',
    'clientSiteWizard.fillOnlyButton': 'Solo rellenar los campos, sin pulsar',
    'clientSiteWizard.loginButton': 'Iniciar sesión',
    'clientSiteWizard.liveButton': 'Acceso en vivo',
    'clientSiteWizard.liveDoneButton': 'Ya entré, continuar',
    'clientSiteWizard.liveRestartButton': 'Reiniciar el acceso en vivo',
    'clientSiteWizard.undoButton': 'Deshacer paso',
    'clientSiteWizard.doneButton': 'Listo',
    'clientSiteWizard.submitButton': 'Enviar a revisión',
    'clientSiteWizard.resumeButton': 'Volver a edición',
    'clientSiteWizard.continueButton': 'Continuar la grabación',
    'clientSiteWizard.discardButton': 'Eliminar borrador',
    'wizardGuide.hintUseless': 'Esto no se entiende',
    'greetingVideoWizard.startSessionButton': 'Empezar a crear el vídeo',
    'greetingVideoWizard.generateScriptButton': 'Generar guion',
    'greetingVideoWizard.generateVideoButton': 'Generar vídeo',
    'greetingVideoWizard.referencesHeading': 'Imágenes de referencia',
    'greetingVideoWizard.scriptHeading': 'Guion',
    'greetingVideoWizard.videoHeading': 'Vídeo',
    'greetingVideoWizard.submitButton': 'Crear proyecto',
    'generationWizard.postprodCtaButton': 'Abrir en Postprod',
  },
};
