/**
 * ГЕНЕРИРУЕТСЯ автоматически — backend/scripts/build-wizard-ui-strings.ts.
 * Не редактировать руками: правки уйдут при следующей сборке. Источник —
 * frontend/src/dictionaries/*.json, список ключей — в самом скрипте.
 */

export const WIZARD_UI_STRINGS: Record<string, Record<string, string>> = {
  ru: {
    'clientSiteWizard.stepUrl': 'Ссылка',
    'clientSiteWizard.stepRecord': 'Запись',
    'clientSiteWizard.stepReview': 'Просмотр',
    'clientSiteWizard.exploreButton': 'Исследовать',
    'clientSiteWizard.fillOnlyButton': 'Только заполнить поля, без нажатия',
    'clientSiteWizard.loginButton': 'Войти',
    'clientSiteWizard.liveButton': 'Живой вход',
    'clientSiteWizard.liveDoneButton': 'Я вошёл — продолжить',
    'clientSiteWizard.liveRestartButton': 'Начать живой вход заново',
    'clientSiteWizard.undoButton': 'Отменить шаг',
    'clientSiteWizard.doneButton': 'Готово',
    'clientSiteWizard.submitButton': 'Отправить на проверку',
    'clientSiteWizard.resumeButton': 'Вернуть в работу',
    'clientSiteWizard.continueButton': 'Продолжить запись',
    'clientSiteWizard.discardButton': 'Удалить черновик',
    'wizardGuide.hintUseless': 'Тут непонятно',
  },
  uk: {
    'clientSiteWizard.stepUrl': 'Посилання',
    'clientSiteWizard.stepRecord': 'Запис',
    'clientSiteWizard.stepReview': 'Перегляд',
    'clientSiteWizard.exploreButton': 'Дослідити',
    'clientSiteWizard.fillOnlyButton': 'Лише заповнити поля, без натискання',
    'clientSiteWizard.loginButton': 'Увійти',
    'clientSiteWizard.liveButton': 'Живий вхід',
    'clientSiteWizard.liveDoneButton': 'Я увійшов — продовжити',
    'clientSiteWizard.liveRestartButton': 'Почати живий вхід заново',
    'clientSiteWizard.undoButton': 'Скасувати крок',
    'clientSiteWizard.doneButton': 'Готово',
    'clientSiteWizard.submitButton': 'Надіслати на перевірку',
    'clientSiteWizard.resumeButton': 'Повернути в роботу',
    'clientSiteWizard.continueButton': 'Продовжити запис',
    'clientSiteWizard.discardButton': 'Видалити чернетку',
    'wizardGuide.hintUseless': 'Тут незрозуміло',
  },
  en: {
    'clientSiteWizard.stepUrl': 'Link',
    'clientSiteWizard.stepRecord': 'Recording',
    'clientSiteWizard.stepReview': 'Review',
    'clientSiteWizard.exploreButton': 'Explore',
    'clientSiteWizard.fillOnlyButton': 'Only fill the fields, no click',
    'clientSiteWizard.loginButton': 'Sign in',
    'clientSiteWizard.liveButton': 'Live sign-in',
    'clientSiteWizard.liveDoneButton': "I'm in — continue",
    'clientSiteWizard.liveRestartButton': 'Start live sign-in over',
    'clientSiteWizard.undoButton': 'Undo step',
    'clientSiteWizard.doneButton': 'Done',
    'clientSiteWizard.submitButton': 'Send for review',
    'clientSiteWizard.resumeButton': 'Return to editing',
    'clientSiteWizard.continueButton': 'Continue recording',
    'clientSiteWizard.discardButton': 'Delete draft',
    'wizardGuide.hintUseless': 'This is unclear',
  },
  de: {
    'clientSiteWizard.stepUrl': 'Link',
    'clientSiteWizard.stepRecord': 'Aufnahme',
    'clientSiteWizard.stepReview': 'Überprüfung',
    'clientSiteWizard.exploreButton': 'Untersuchen',
    'clientSiteWizard.fillOnlyButton': 'Nur Felder ausfüllen, ohne Klick',
    'clientSiteWizard.loginButton': 'Anmelden',
    'clientSiteWizard.liveButton': 'Live-Anmeldung',
    'clientSiteWizard.liveDoneButton': 'Ich bin drin — weiter',
    'clientSiteWizard.liveRestartButton': 'Live-Anmeldung neu starten',
    'clientSiteWizard.undoButton': 'Schritt rückgängig',
    'clientSiteWizard.doneButton': 'Fertig',
    'clientSiteWizard.submitButton': 'Zur Prüfung senden',
    'clientSiteWizard.resumeButton': 'Zurück in Bearbeitung',
    'clientSiteWizard.continueButton': 'Aufzeichnung fortsetzen',
    'clientSiteWizard.discardButton': 'Entwurf löschen',
    'wizardGuide.hintUseless': 'Das ist unklar',
  },
  es: {
    'clientSiteWizard.stepUrl': 'Enlace',
    'clientSiteWizard.stepRecord': 'Grabación',
    'clientSiteWizard.stepReview': 'Revisión',
    'clientSiteWizard.exploreButton': 'Explorar',
    'clientSiteWizard.fillOnlyButton': 'Solo rellenar los campos, sin pulsar',
    'clientSiteWizard.loginButton': 'Iniciar sesión',
    'clientSiteWizard.liveButton': 'Acceso en vivo',
    'clientSiteWizard.liveDoneButton': 'Ya entré, continuar',
    'clientSiteWizard.liveRestartButton': 'Reiniciar el acceso en vivo',
    'clientSiteWizard.undoButton': 'Deshacer paso',
    'clientSiteWizard.doneButton': 'Listo',
    'clientSiteWizard.submitButton': 'Enviar a revisión',
    'clientSiteWizard.resumeButton': 'Volver a edición',
    'clientSiteWizard.continueButton': 'Continuar la grabación',
    'clientSiteWizard.discardButton': 'Eliminar borrador',
    'wizardGuide.hintUseless': 'Esto no se entiende',
  },
};
