/**
 * Тексты панели редактора голосовой карты — English (`en`). Ленивый
 * чанк `editor-panel-en.js` (заход 10): панель берёт его `import()` по
 * `ready` пикера с языком страницы `en`. Сверка ключей — scripts/editor.test.ts.
 */
import type { Dict } from './i18n';

const D: Dict = {
  linkBad:
    'The editor link is invalid or already used — get a new one in Telegram.',
  expired:
    'The editor session has ended — open the editor again from Telegram.',
  tabTarget: 'Target',
  tabPage: 'Page',
  tabTry: 'Try',
  tabPublish: 'Publish',
  pickHint:
    'Hover a button or link on the page and click it — the target card opens here. The site ignores the click (Select mode).',
  key: 'Key (latin)',
  names: 'Voice name',
  synonyms: 'Synonyms (comma-separated)',
  type: 'Type',
  risk: 'Risk',
  riskNow: 'Right away',
  riskConfirm: 'With confirmation',
  riskNever: 'Never',
  riskAuto: 'As the code decides',
  deny: 'Deny — the assistant touches nothing here',
  control: 'Control command (re-check after site changes)',
  scope: 'Applies to',
  scopePage: 'This page',
  scopeTemplate: 'Page template',
  scopeSite: 'Whole site',
  newTemplate: 'New template by mask',
  undo: 'How to undo (data-assist-id of the reverse button)',
  save: 'Save to draft',
  remove: 'Remove from map',
  restore: 'Restore',
  saved:
    'Saved to draft (revision {n}). Publishing needs confirmation in Telegram.',
  conflict: 'The map was changed in another tab — reloading.',
  invalid: 'Not saved: {e}',
  riskLowering: 'risk can only be raised',
  neverNamed: 'a “never” target can only be denied — no names',
  neverAttr: 'element under data-assist="never" — deny only',
  textInvalid:
    'text failed validation (links, markup, “ignore instructions”, personal data)',
  never: 'The assistant will never press this (K-10) — you can only deny it.',
  fragile:
    'Low reliability: the assistant will ask first. Markup makes it press right away.',
  snippet: 'Line for the developer:',
  copy: 'Copy',
  computed: 'Code decided: {r}',
  empty: 'No map targets on this page yet.',
  check: 'Check on this page',
  found: 'found {n}',
  sayPh: 'Say or type a command as a visitor would',
  say: 'Try',
  via_map: 'Understood via the map: “{p}” → {k}',
  via_direct: 'Understood without the model (visible text).',
  via_model_needed:
    'Here the assistant would ask the model — test it with the T-2 wizard.',
  via_none: 'Not understood as a command.',
  miss: 'Map target “{k}” is not found on this page.',
  wrong: 'Wrong → pick the right target',
  wrongPick:
    'Click the right target on the page — the phrase becomes its synonym.',
  stepsNone: 'No steps.',
  left: 'Checks left today: {n}',
  gatesOk: 'Gates: green',
  gatesBad: 'Gates: {n} problems',
  request: 'Request publishing',
  requested: 'Version v{n} built ({s}). Confirm publishing in Telegram.',
  undoLast: 'Undo the last change',
  counts: '🟩 {g} · 🟨 {y} · 🟥 {r} · 🟪 {v}',
  exit: 'Exit the editor',
  exited: 'Editor closed. The draft is saved — publish it in Telegram.',
  version: 'Published v{v} · revision {r}',
  tabMemo: 'Memo',
  mIntro:
    '“Record” → click on the site: a click is a step, a field is a parameter without its value.',
  mRec: 'Record',
  mStop: 'Pause',
  mSave: 'Save draft',
  mTry: 'Run',
  mNew: 'New',
  mName: 'Memo name',
  mGoal: 'Goal: what is there at the end',
  mHint: 'Recording: navigation and expanding run, submits do not.',
  mOn: '● Recording',
  mOpened: 'M-{n}: step → ⌖ to rebind.',
  mRebind: 'Click the new element for the step.',
  mNever: 'Never — recording stopped',
  mManual: 'The visitor presses it — recording stopped',
  mMax: 'Step limit — recording stopped',
  mSaved: 'Draft M-{n} saved (gate problems: {p}). Publish in Telegram.',
  mFail: 'Step {n} failed: {p}',
  mNext: 'Step {n} is on {p}: go there and Run.',
  mDone: 'All steps and the goal are in place.',
  mGoalMiss: 'The goal is not visible on the page.',
  p_missing: 'element not found',
  p_ambiguous: 'several identical',
  p_pin_mismatch: 'element changed',
  p_risk_up: 'became riskier',
  p_never: 'the action is forbidden',
  mWait: 'Wait for this',
  mWaitHint: 'Click what should appear.',
  mCnt: 'Counter',
  search: 'Find target ( / )',
  bulk: 'Selected: {n}',
  bAdd: 'Add to map',
  bDeny: 'Deny',
  bRisk: 'Raise risk',
  bCtl: 'Control',
  bTpl: 'To template',
  s_draft: 'draft',
  s_checking: 'checking',
  s_published: 'published',
  s_held: 'held',
  s_needs_review: 'needs review',
  s_disabled: 'disabled',
  tabMiss: 'Misses',
  tabSugg: 'Suggestions',
  aiSyn: '✨ AI synonyms',
  loading: 'Loading…',
  loadFail: 'Failed to load.',
  retry: 'Retry',
};

export default D;
