/**
 * Prompt Types
 *
 * Defines text-to-video prompt structures and moderation status.
 */

/**
 * Content moderation status
 */
export enum ModerationStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  FLAGGED = 'flagged',
  BYPASSED = 'bypassed', // User explicitly approved despite flags
}

/**
 * GenerationPrompt represents the text-to-video prompt for Sora 2
 */
export interface GenerationPrompt {
  /** Unique identifier (UUID) */
  promptId: string;

  /** AI-generated prompt text */
  generatedText: string;

  /** User's edited version (if modified, optional) */
  userEditedText?: string;

  /** Final approved text (generated or edited) */
  finalText: string;

  /** Character count of final text */
  characterCount: number;

  /** Timestamp when generated by AI */
  generatedAt: Date;

  /** Timestamp when approved by user (optional) */
  approvedAt?: Date;

  /** Content moderation result */
  moderationStatus: ModerationStatus;

  /** Flagged content categories (if any, optional) */
  moderationFlags?: string[];

  /**
   * Текст озвучки как отдельная сущность (ТЗ §15.2, этап 35).
   *
   * До этапа 35 реплики жили строкой внутри `finalText` и своей жизни не
   * имели — их читал Veo. Как только речь синтезируем мы, текст обязан
   * быть виден и правим ДО синтеза: переслушать дороже, чем перечитать.
   *
   * `voiceoverScript` — что вернула модель, `voiceoverScriptEdited` —
   * правка пользователя, `finalVoiceoverScript` — то, что уйдёт в синтез.
   * Три поля, а не одно, по той же причине, что и у самого промпта:
   * сравнить исходное с правленым иногда единственный способ понять, что
   * пошло не так.
   */
  voiceoverScript?: string;
  voiceoverScriptEdited?: string;
  finalVoiceoverScript?: string;
  /** Откуда взялся текст: из отдельного поля ответа или из реплик промпта. */
  voiceoverScriptSource?: 'field' | 'dialogue' | 'none';
}
