/**
 * Prompt Types
 *
 * Defines text-to-video prompt structures and moderation status.
 */

/**
 * Content moderation status
 */
export enum ModerationStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  FLAGGED = 'flagged',
  BYPASSED = 'bypassed', // User explicitly approved despite flags
}

/**
 * GenerationPrompt represents the text-to-video prompt for Sora 2
 */
export interface GenerationPrompt {
  /** Unique identifier (UUID) */
  promptId: string;

  /** AI-generated prompt text */
  generatedText: string;

  /** User's edited version (if modified, optional) */
  userEditedText?: string;

  /** Final approved text (generated or edited) */
  finalText: string;

  /** Character count of final text */
  characterCount: number;

  /** Timestamp when generated by AI */
  generatedAt: Date;

  /** Timestamp when approved by user (optional) */
  approvedAt?: Date;

  /** Content moderation result */
  moderationStatus: ModerationStatus;

  /** Flagged content categories (if any, optional) */
  moderationFlags?: string[];

  /**
   * Текст озвучки как отдельная сущность (ТЗ §15.2, этап 35).
   *
   * До этапа 35 реплики жили строкой внутри `finalText` и своей жизни не
   * имели — их читал Veo. Как только речь синтезируем мы, текст обязан
   * быть виден и правим ДО синтеза: переслушать дороже, чем перечитать.
   *
   * `voiceoverScript` — что вернула модель, `voiceoverScriptEdited` —
   * правка пользователя, `finalVoiceoverScript` — то, что уйдёт в синтез.
   * Три поля, а не одно, по той же причине, что и у самого промпта:
   * сравнить исходное с правленым иногда единственный способ понять, что
   * пошло не так.
   */
  voiceoverScript?: string;
  voiceoverScriptEdited?: string;
  finalVoiceoverScript?: string;
  /** Откуда взялся текст: из отдельного поля ответа или из реплик промпта. */
  voiceoverScriptSource?: 'field' | 'dialogue' | 'none';

  /**
   * Текстовые моменты на экране (ТЗ VEO-MODEL-VERSION-CHOICE-SPEC.md
   * §20.2, оживление никогда не сделанного Этапа 3 из §8.5 п.1) —
   * извлечены отдельным, дешёвым вызовом (`extractLiteralTexts()`,
   * `prompt.service.ts`) ПОСЛЕ основной сборки промпта. Пустой массив
   * или `undefined` — ролик не нуждается в тексте на экране вовсе.
   * Каждый момент — кандидат на свою text-card (§20.3); что реально
   * стало карточкой — не здесь, отдельная сущность на сессии (не
   * реализовано в этом заходе, см. ТЗ §20.7).
   */
  onScreenTextMoments?: OnScreenTextMoment[];
}

/**
 * Один текстовый момент на экране — не диалог/озвучка, а именно
 * НАДПИСЬ в кадре (§20.2 ТЗ). `role` определяет приоритет слота
 * референс-изображений (§20.4 п.1: персонажи > cta > hook > callout)
 * и визуальный акцент карточки (§20.3: у cta есть акцентная плашка).
 */
export interface OnScreenTextMoment {
  /** ≤100 символов (§8.5 п.3 ТЗ) — короче для карточек, которые
   * реально должны читаться, а не быть частью общего фона. */
  text: string;
  role: 'hook' | 'callout' | 'cta';
  /**
   * Заполняется ОТДЕЛЬНЫМ, более поздним шагом (не
   * `extractLiteralTexts()`, который знает только текст+роль) —
   * рендер через `common/text-card-render.ts` и заливка в Blob
   * (§20.3 ТЗ). `undefined` — карточка ещё не отрендерена (или
   * рендер не удался — best-effort, тот же принцип, что и у самого
   * извлечения текста).
   */
  cardPathname?: string;
  cardUrl?: string;
  /**
   * Хэш текста+роли на момент рендера карточки (§20.4 п.4) — сверяется
   * при открытии экрана генерации; расхождение с текущим `text`
   * значит «текст поменяли после рендера карточки, она устарела».
   */
  cardTextHash?: string;
}
